server:
    port: 8080
    servlet:
        context-path: /identity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
    signer-key: "/10o6hUx7oSBfY2jtmNH49y0RiTDgTdkvkbVa+lidNNvzRdRK+uZt0Cwe0um0vJr\n"
    valid-duration: 3600 # ins second
    refreshable-duration: 86400 # seconds